---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sleenegb/public_html/sleekacademianewsite/
    - /bin/mkdir -p $DEPLOYPATH
    - /usr/bin/rsync -av --delete --exclude='.git' --exclude='.cpanel.yml' --exclude='node_modules' ./ $DEPLOYPATH
