---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sleenegb/public_html/sleekacademianewsite
    - export NODEBIN=/opt/alt/alt-nodejs20/root/usr/bin
    - export NPM=/opt/alt/alt-nodejs20/root/usr/bin/npm
    - export PATH=$NODEBIN:$PATH
    - /bin/mkdir -p $DEPLOYPATH
    - /usr/bin/rsync -av --delete --exclude='.git' --exclude='.cpanel.yml' --exclude='node_modules' --exclude='.env' ./ $DEPLOYPATH
    - cd $DEPLOYPATH && $NPM install --omit=dev
    - /bin/mkdir -p $DEPLOYPATH/tmp
    - /bin/touch $DEPLOYPATH/tmp/restart.txt
